<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tpetrov-PC" name="com.sirma.itt.javacourse.javaobjects.test.TestSumatorFloats" tests="4" failures="0" timestamp="9 Sep 2014 12:27:00 GMT" time="0.031" errors="1">
  <testcase name="getSum" time="0.000" classname="com.sirma.itt.javacourse.javaobjects.test.TestSumatorFloats"/>
  <testcase name="getSum" time="0.000" classname="com.sirma.itt.javacourse.javaobjects.test.TestSumatorFloats"/>
  <testcase name="getSum" time="0.015" classname="com.sirma.itt.javacourse.javaobjects.test.TestSumatorFloats">
    <error type="java.lang.AssertionError" message="expected [7.65] but found [7.6499996]">
      <![CDATA[java.lang.AssertionError: expected [7.65] but found [7.6499996]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sirma.itt.javacourse.javaobjects.test.TestSumatorFloats.getSum(TestSumatorFloats.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- getSum -->
  <testcase name="getSum" time="0.016" classname="com.sirma.itt.javacourse.javaobjects.test.TestSumatorFloats"/>
</testsuite> <!-- com.sirma.itt.javacourse.javaobjects.test.TestSumatorFloats -->
